import { GatewayIntentBits } from 'discord.js'
import { BrowserWindow } from 'electron'

export interface ClientOptions {
	appWindow: BrowserWindow
	privilegedIntents: GatewayIntentBits[]
}

export enum ClientErrorCodes {
	CLIENT_NOT_READY = 'CLIENT_NOT_READY',
	NOT_GUILD_CHANNEL = 'NOT_GUILD_CHANNEL',
	NOT_TEXT_BASED_CHANNEL = 'NOT_TEXT_BASED_CHANNEL',
	NO_CURRENT_CHANNEL = 'NO_CURRENT_CHANNEL',
	CANNOT_FETCH_GUILD = 'CANNOT_FETCH_GUILD',
	NO_VIEWABLE_CHANNEL_IN_GUILD = 'NO_VIEWABLE_CHANNEL_IN_GUILD',
	CANNOT_FETCH_CHANNEL = 'CANNOT_FETCH_CHANNEL',
	MISSING_PERMISSIONS = 'MISSING_PERMISSIONS',
	INCORRECT_IPC_CHANNEL = 'INCORRECT_IPC_CHANNEL',
	CANNOT_FETCH_USER = 'CANNOT_FETCH_USER',
	CANNOT_CREATE_DM = 'CANNOT_CREATE_DM',
	NO_SELECTED_CHANNEL = 'NO_SELECTED_CHANNEL',
}
