name: Feature Request
description: Have an idea for a new feature? Create an issue to suggest
title: 'Feature: '
labels: ['Feature: New']
assignees:
  - darkguy10
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve the BotClient! <img src="https://cdn.discordapp.com/emojis/816599114740924459.webp?size=96&quality=lossless" alt=":AE_HeartHug:" title=":AE_HeartHug:" height="22" width="22"  />
        Please consider checking out with our peeps over at the [BotClient Support Server](https://discord.com/invite/aZSrxwNUFD) before filing your request. <img src="https://cdn.discordapp.com/emojis/898284896102015006.webp?size=96&quality=lossless" alt=":ChillBar_point_right:" title=":ChillBar_point_right:" height="22" width="22"  />
  - type: checkboxes
    attributes:
      label: Issue checklist
      options:
        - label: I have searched the existing issues to make sure this isn't a duplicate.
          required: true
        - label: I have discussed this feature on the support server.
          required: false
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: |
        A clear and concise description of what the problem is, or what feature you want to be implemented.
      placeholder: |
        I'd love to see [something] added to the client.
        It'd be really helpful if [something] was implemented.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Ideal solution or implementation
      description: |
        A clear and concise description of what exactly you want to happen.
      placeholder: |
        The [something] thingy should do [something something] in a [certain] way.
    validations:
      required: true
  - type: textarea
    id: alternate-solution
    attributes:
      label: Alternate solution or implementation
      description: A clear and concise description of any alternative solutions or features you have considered.
      placeholder: |
        Alternatively, it can achieved in [this] way.
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other context, screenshots, or file uploads that help us understand your feature request.
